controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints: [joint1, joint2, joint3, joint4]
    command_interfaces: [position]
    state_interfaces: [position, velocity]
    allow_partial_joints_goal: false
    constraints:
      goal_time: 1.0
      stopped_velocity_tolerance: 0.01
    gains:   # harmless if ignored by GazeboSystem
      joint1: {p: 50.0, d: 1.0}
      joint2: {p: 40.0, d: 0.8}
      joint3: {p: 40.0, d: 0.8}
      joint4: {p: 30.0, d: 0.5}
